mysql:
  dsn: root:136szssl668AAA0@tcp(43.136.120.152:3306)/imchat?charset=utf8mb4&parseTime=True&loc=Local
redis:
  addr: "43.136.120.152:6379"
  password: "8957086"
  DB: 0
  poolSize: 30
  minIdleConn: 30
  
